### ISSUE TITLE
Browser support question / Reflect usage

### ISSUE THREAD

**Issue by petetnt** [snovakovic/js-flock#52]
Hi! First of all: awesome library!

I was looking into a unrelated `deepFreeze` issue when I found `js-flock`, which recommended elsewhere. Turns out that [IE11 doesn't support Reflect](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Reflect), which was first added in https://github.com/snovakovic/js-flock/pull/37 which means that IE11 support is out of the question without polyfills.

Is the IE11 support out of the question in general / on purpose, or is there some other way to fix the issue in #37 without relying on Reflect?

Thanks a lot!

**Comment by snovakovic** [comment]
@petetnt first of all sorry for late reply!

Actually truth is that it's very easy to fix #37 without relying on Reflect. I kind of regret decision of using Reflect for exact same reasons you described in issue.

**Comment by snovakovic** [comment]
@petetnt I have remove reflect usage from deepFreeze and publish new version. It's should work in IE11 from version 3.1.6. Disclaimer: I haven't actually tested it in IE11 as I don't have access to IE11 at this point.

I'll close the Issue and in case there is any other issue you can reopen it. 

Just one more note by default `js-flock` is exporting unmodified ES6 code so when used in browser you will have to load transpiled version of code as described in documentation e.g `const sort = require('js-flock/es5/deepFreeze');` or you can run it through your bable build process depending on your preferences. Let me know if you have any questions regarding that.
