### ISSUE TITLE
I would like a syntax for sorting some properties ascending and others descending

### ISSUE THREAD

**Issue by ericpyle** [snovakovic/js-flock#56]
For instance, I'd like to sort ascending by name, and then under each duplicate name, list them as more recent first.

Could be done with something like the following (but you'd need something that scales well):

`sort(bundles).by([ { asc: [b => b.name] }, { desc: [b=>revision] } ]);`

Right now, it seems like I have to do two sorts in order to make some properties descending and other ascending. So, I (think I) can accomplish this with two sorts, though in an awkward order:
 
`sort(sort(bundles).desc([b => b.revision])).asc([b => b.name]);`

I suppose I could add a pseudo (decorator) property called `age` that is the reverse of revision, so the newest revisions get listed first.

`sort(bundles).asc([b => b.name, b=>age]);`

or 

`sort(bundles).asc([b => b.name, b=>(1 / revision)]);`

**Comment by snovakovic** [comment]
@ericpyle 
The same feature has already been requested but in `fast-sort` branch (https://github.com/snovakovic/fast-sort/issues/2). Sorry about confusion with repositories. (fast-sort) is just exported sort from here as a single module.

It's definitely something I want to implement/support (I will try to tackle it next week). I have to consider performance impact and see what will work best.

**Comment by ericpyle** [comment]
@snovakovic thanks for the feedback! I'm in no hurry for this feature, but glad to see others have expressed interest.

**Comment by snovakovic** [comment]
@ericpyle sorting in multiple direction is available from version `3.5.0`

The syntax for sorting in multiple direction is 

```javascript
  sort(persons).by([
    { asc: 'name' }
    { desc: 'age' }
    { asc: p => p.address.city }
  ]);
```

Another new thing is that we are now able to provide property name as a string key. (It's available only for root object properties. In case of nested properties we still have to use function syntax as is the case for `address.city` in previous example)

that means that 
`sort(persons).asc(p => p.name)` can now be written shorter as `sort(persons).asc('name')`. The other benefit of providing string vs function is that it is slightly more perfomrant.

**Comment by snovakovic** [comment]
Implemented from version `3.5.0`

**Comment by tony-gutierrez** [comment]
I'm trying to use this, but it seems like the second array value changes the direction of the first sometimes.

**Comment by snovakovic** [comment]
Hi tony,

I got email regarding sorting issue but can't find a thread on it (might be
deleted?)

In case you still experiance issue coud you provide example array that it
happens on and I will take a look.

Have a nice day!

**Comment by tony-gutierrez** [comment]
Hey, thanks for the response. It turned out that the sort was working great, but my ui data display was off and leading me to think there was a problem. Love the library! Was able to send an array of functions into .by() that would return the desired sort dir/field, and it all worked great!

**Comment by snovakovic** [comment]
Cool, glad to hear that!
