### ISSUE TITLE
Working incorrectly with character and number

### ISSUE THREAD

**Issue by aquocbao** [snovakovic/js-flock#63]
version: 1.5.3
I have a JSON object like this:
let data = `[
  {"id":1, 
  "name": "HS_1"
  },
  {"id":1, 
  "name": "HS_10"
  },
   {"id":1, 
  "name": "HS_11"
  },
   {"id":1, 
  "name": "HS_2"
  }
]
const sortJsonArray = require('fast-sort');
response = sortJsonArray(data).asc((p) => p.name);
`
The response is `[
  {"id":1, 
  "name": "HS_1"
  },
  {"id":1, 
  "name": "HS_10"
  },
   {"id":1, 
  "name": "HS_11"
  },
   {"id":1, 
  "name": "HS_2"
  }
]`

It should be `[
  {"id":1, 
  "name": "HS_1"
  },
  {"id":1, 
  "name": "HS_2"
  },
   {"id":1, 
  "name": "HS_10"
  },
   {"id":1, 
  "name": "HS_11"
  }
]`
Please help us to reivew it. Thanks

**Comment by snovakovic** [comment]
@aquocbao There is nothing wrong with the sorting form the above. It is working exactly as it suppose to work as that's how sorting of string works. `HS_1` is not character and number it is string and it is treated as such (no matter that it contains number inside of it). and when sorting strings `HS_10` comes before `HS_2` no matter if that's not what you would logically expect. 

If you try native JavaScript sorting `['HS_10', 'HS_1', 'HS_11', 'HS_2'].sort()` You will get exact same result... (or if you try any other library out there it will still produce same result)

If you want to get logical result (results you would expect) you will need to divide string and number and sort them on those two properties independently. 

For the example above something as this would produce desired sorting

```javascript
    sortJsonArray(data).asc([
      (p) => p.name.split('_')[0], // First sort by string part (HS)
      (p) => Number(p.name.split('_')[1]) // Then sort by number part as a number
    ]);
```

NOTE: The above is just a quick example and not something I'm recommending to actually use in production code as it is much slower then just doing `sortJsonArray(data).asc((p) => p.name)`. In case data set to sort is not huge even something as the above should be perfectly fine. Your data set can differ from example of the above so it's is possible it will work only on the example above but not on your actual data set.

Hope this helps at least some. I will close the issue as there is nothing wrong with the sort library.

**Comment by aquocbao** [comment]
Many thanks. :)
